# Generated by Django 4.0.3 on 2022-04-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='text',
        ),
    ]
